# Generated by Django 3.2.7 on 2022-01-20 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='company',
        ),
    ]
